### ISSUE TITLE
上传code问题

### ISSUE THREAD

**Issue by PeterGooo** [PeterGooo/notes#1]
今晚我上传代码，不知道怎么处理了，昨天讲的多了。说实在的没有记得清楚。

**Comment by DavidFeng** [comment]
* git pull： 从远程仓库获取更新，并应用更新。（拉取到本地）
* git push：本地提交后推送提交到上游。

* git add：添加改变到stage 暂存区

* git commit：将暂存区的内容确认提交

* git status：查看仓库状态

* git log：查看仓库历史 可以加选项 -p 详细历史 -数字N 查看n条历史
