### ISSUE TITLE
javascript   status显示问题

### ISSUE THREAD

**Issue by PeterGooo** [PeterGooo/notes#2]
<!DOCTYPE html>
<html>
<head>
	<title>javascript</title>
	<meta charset="utf-8">
</head>
<body>
<script>
// for(x in document){
// 	document.write(x + "<br>");
// }
</script>
<p  onmouseover ="status='状态栏';" onmouseout="status = '';">点击呀</p>
</body>
</html>

这个状态栏不会显示，我自己在代码里面没有检查出错误，并且我也没有查到原因，还有，我试了两个浏览器。    onmouseover= “alert（‘   ’）”时是可以的

**Comment by PeterGooo** [comment]
<!DOCTYPE html>
<html>
<head>
	<title>javascript</title>
	<meta charset="utf-8">
</head>
<script>

</script>
<body onload="setInterval('show()',2000);">
<img name= "anm" src="0.png" width="300"></img>
<script>
var images = new Array(4);
var indext = 2;
for(var i=0; i<4; i++){
	images[i] = new image();
	images[i].src = i + ".png";
}
	function show(){
	document.anm.src=images[indext].src;
	indext=(indext+1)%4;
}

</script>
</body>
</html>

这个body中的onload，在页面中没有效果

**Comment by DavidFeng** [comment]
onload中的调用·setInterval·设置的定时器回调是有效果的，只不过你代码中有其他错误，才会出现你说的“没有效果”，

你要学会使用浏览器的 < ctrl + shift + i>功能打开调试器查看。

这个你知道吧？就是在页面右键点击后出现的查看元素功能， 我之前给你演示过好多次的。

然后打开console，就能看到报错了， 然后根据报错信息修改吧，

要学会自己排错，debug

**Comment by DavidFeng** [comment]
![t](https://cloud.githubusercontent.com/assets/158052/15697467/f3661026-27ec-11e6-9565-a4fd36ca3edd.gif)

**Comment by DavidFeng** [comment]
第一个例子， 看这里 http://www.w3school.com.cn/jsref/prop_win_status.asp

```
status 属性是一个可读可写的字符串，声明了要在窗口状态栏中显示的一条消息。
通常显示这条消息的时间是有限的，
直到其他的消息将它覆盖，或者用户把鼠标移动到窗口的其他区域为止。
当擦除了 status 声明的消息时，状态栏要么恢复为它默认的空白状态，
要么是再次显示出属性 defaultStatus 声明的默认消息。
据我们所知，不少浏览器已经关闭了脚本化它们的状态栏的功能。
这是一项安全措施，防止隐藏了超链接真正目的的钓鱼攻击。
```

就是说现在的主流浏览器已经不支持这个特性了，你的这个教程太老了

**Comment by PeterGooo** [comment]
ok
